services:
  db:
    image: postgres:15
    container_name: chat-db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 2s
      timeout: 2s
      retries: 3
    volumes:
      - "./db:/var/lib/postgresql/data"
    ports:
      - "5433:5432"

#  test_db:
#    image: postgres:15
#    container_name: chat-test-db
#    environment:
#      POSTGRES_DB: db_for_tests
#      POSTGRES_USER: test_user
#      POSTGRES_PASSWORD: test_password
#    ports:
#      - "5434:5432"

  web:
    environment:
      ENCODING_KEY: ${ENCODING_KEY}
      ACCESS_TOKEN_EXPIRATION_TIME_IN_MINUTES: ${ACCESS_TOKEN_EXPIRATION_TIME_IN_MINUTES}
      REFRESH_TOKEN_EXPIRATION_TIME_IN_DAYS: ${REFRESH_TOKEN_EXPIRATION_TIME_IN_DAYS}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    build: .
    container_name: chat-web
    ports:
      - "8000:8000"
    volumes:
      - "./app:/opt/app"
    depends_on:
      db:
        condition: service_healthy
